apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pvc
  namespace: jenkins-ns
spec:
  volumeMode: Filesystem
  storageClassName: jenkins-volume-storage-class 
  resources:
    requests:
      storage: 2Gi
  accessModes:
    - ReadWriteOnce