apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: jenkins-volume-storage-class
provisioner: kubernetes.io/gce-pd
reclaimPolicy: Delete
parameters:
  type: pd-standard
  fstype: ext4
  replication-type: none